version: '3.8'

services:
  
  app:
    build:
      context: .
    env_file:
      - .env-non-dev
    container_name: fastapi_app
    command: ["/fastapi_app/docker/app.sh"]
    ports:
      - 9999:8000
    depends_on:
      - db
      - redis
  
  redis:
    image: redis:7
    container_name: redis_app
    env_file:
      - .env-non-dev
  
  celery:
    build:
      context: .
    container_name: celery_app
    depends_on:
      - redis
    command: ["/fastapi_app/docker/celery.sh", "celery"]
    env_file:
      - .env-non-dev

  flower:
    build:
      context: .
    container_name: flower_app
    depends_on:
      - redis
      - celery
    command: ["/fastapi_app/docker/celery.sh", "flower"]
    ports:
      - 8888:5555
    env_file:
      - .env-non-dev
  
  db:
    image: postgres:15
    container_name: db_app
    env_file:
      - .env-non-dev
  